name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run
      uses: ./
    - name: test
      if: "!${{steps.run.outputs.should_publish}}"
      run: |
        echo "::error file={name},line={line},endLine={endLine},title={title}::${{ steps.run.outputs }}"
        exit 1